package io.github.michelbr84.flapforge.android;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.junit.Test;

/**
 * Holds the living docs to the size of this suite.
 *
 * <p>The M10 gate counts the test cases in the JUnit XML and the docs quote that figure, so a
 * change that adds a test and leaves the docs alone ships a stale number: {@code ROADMAP.md}
 * still said 223 after the record hotfix had grown the suite to 233. This test counts the
 * same thing from the sources — the {@code @Test} methods, and the classes carrying at least
 * one — and checks the two living claims against it: {@code DEVELOPMENT.md}'s "the M10 suite
 * is N tests in M classes" and {@code ROADMAP.md}'s "N tests (JUnit 4, ...)". {@code
 * CHANGELOG.md} is history and is left alone. The source count equals the XML count as long
 * as no test is parameterised, ignored or generated by a runner, which none is; the first
 * such test has to be counted here too.
 */
public class SuiteInventoryTest {

    private static final String ANDROID_BUILD_FILE = "android/build.gradle";
    private static final String TEST_ROOT = "android/src/test/java";
    private static final String DEVELOPMENT_DOC = "docs/DEVELOPMENT.md";
    private static final String ROADMAP_DOC = "docs/ROADMAP.md";
    /** A JUnit 4 test method: the annotation alone at the start of a line, never in a comment. */
    private static final Pattern TEST_ANNOTATION = Pattern.compile("(?m)^[ \\t]*@Test\\b");
    /** DEVELOPMENT.md ("Android build"): the sentence the gate's count is quoted in. */
    private static final Pattern DEVELOPMENT_CLAIM =
            Pattern.compile("the M10 suite is (\\d+) tests in\\s+(\\d+) classes");
    /** ROADMAP.md (M10 summary): the test count next to the runner. */
    private static final Pattern ROADMAP_CLAIM = Pattern.compile("(\\d+) tests \\(JUnit 4");
    /** The suite the record hotfix closed with; a scan that finds fewer is broken, not smaller. */
    private static final int HOTFIX_TESTS = 233;

    @Test
    public void docsStateTheCurrentSuiteSize() throws IOException {
        Path root = repoRoot();
        Map<String, Integer> perClass = countTests(root.resolve(TEST_ROOT));
        int tests = perClass.values().stream().mapToInt(Integer::intValue).sum();
        int classes = perClass.size();
        assertTrue("the scan found " + tests + " tests, fewer than the " + HOTFIX_TESTS
                + " the hotfix closed with: " + perClass, tests >= HOTFIX_TESTS);

        int[] development = numbers(DEVELOPMENT_CLAIM, read(root.resolve(DEVELOPMENT_DOC)),
                DEVELOPMENT_DOC);
        assertEquals(DEVELOPMENT_DOC + " test count; the sources have " + perClass,
                tests, development[0]);
        assertEquals(DEVELOPMENT_DOC + " class count; the sources have " + perClass.keySet(),
                classes, development[1]);

        int[] roadmap = numbers(ROADMAP_CLAIM, read(root.resolve(ROADMAP_DOC)), ROADMAP_DOC);
        assertEquals(ROADMAP_DOC + " test count; the sources have " + perClass,
                tests, roadmap[0]);
    }

    /** Test methods per test class (simple name), for every source file carrying at least one. */
    private static Map<String, Integer> countTests(Path testRoot) throws IOException {
        List<Path> sources;
        try (Stream<Path> walk = Files.walk(testRoot)) {
            sources = walk.filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith(".java"))
                    .collect(Collectors.toList());
        }
        Map<String, Integer> perClass = new TreeMap<>();
        for (Path source : sources) {
            int count = 0;
            Matcher m = TEST_ANNOTATION.matcher(read(source));
            while (m.find()) {
                count++;
            }
            if (count > 0) {
                String name = source.getFileName().toString();
                perClass.put(name.substring(0, name.length() - ".java".length()), count);
            }
        }
        return perClass;
    }

    /** The numbers captured by the pattern's only match in the document. */
    private static int[] numbers(Pattern pattern, String text, String document) {
        Matcher m = pattern.matcher(text);
        assertTrue(document + " states the suite size (pattern " + pattern + ")", m.find());
        int[] values = new int[m.groupCount()];
        for (int i = 0; i < values.length; i++) {
            values[i] = Integer.parseInt(m.group(i + 1));
        }
        assertFalse(document + " states the suite size once, not twice (pattern " + pattern
                + ")", m.find());
        return values;
    }

    /** The repository root: the directory holding the Android build file, at or above cwd. */
    private static Path repoRoot() {
        Path dir = Path.of(System.getProperty("user.dir", ".")).toAbsolutePath().normalize();
        for (Path p = dir; p != null; p = p.getParent()) {
            if (Files.isRegularFile(p.resolve(ANDROID_BUILD_FILE))) {
                return p;
            }
        }
        throw new IllegalStateException(ANDROID_BUILD_FILE + " not found at or above " + dir);
    }

    private static String read(Path file) throws IOException {
        return new String(Files.readAllBytes(file), StandardCharsets.UTF_8);
    }
}
