package io.github.michelbr84.flapforge.render;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import io.github.michelbr84.flapforge.persistence.JsonCodec;
import java.awt.AWTError;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsEnvironment;
import java.awt.Transparency;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.imageio.ImageIO;

/**
 * The one door original art and sound may enter through (D18).
 *
 * <p>Everything Flapforge draws is generated by {@link ProceduralArt}; an asset is an
 * <em>override</em> of one id, and the only place an id can be declared is
 * {@code assets/manifest.json}:
 *
 * <pre>{@code
 * { "version": 1,
 *   "assets": [ { "id": "bird/classic", "path": "sprites/birds/classic.png",
 *                 "kind": "SPRITE", "license": "CC0-1.0", "source": "drawn for Flapforge" } ] }
 * }</pre>
 *
 * <p>Rules this class keeps, all of them deliberate:
 * <ul>
 *   <li>ids resolve <b>only</b> through the manifest — nothing ever scans a directory, so a file
 *       dropped into {@code assets/sprites/} without a manifest entry is inert and no licence
 *       can enter the build unnoticed;</li>
 *   <li>loading goes through {@link Class#getResourceAsStream} (works inside the jar) with
 *       {@link ImageIO#setUseCache(boolean) ImageIO.setUseCache(false)}, so decoding never
 *       writes a temporary file;</li>
 *   <li>an image is converted to a screen-compatible one when a {@link GraphicsConfiguration}
 *       exists and kept as a plain {@link BufferedImage} when the JVM is headless, so the same
 *       code path serves the game and the headless render tests;</li>
 *   <li>every result is cached by id, misses included, and returned as an {@link Optional} — a
 *       manifest entry pointing at a resource that is not there is an <em>error in
 *       {@link #errors()}</em>, never an exception, and the caller falls back to procedural art.
 *       </li>
 * </ul>
 * The shipped manifest carries an empty list, so {@link #sprite(String)} always answers empty and
 * every renderer draws procedurally.
 */
public final class AssetManager {

    /** Classpath location of the manifest. */
    public static final String MANIFEST_RESOURCE = "/assets/manifest.json";
    /** Classpath prefix every manifest path is resolved against. */
    public static final String ASSET_ROOT = "/assets/";
    /** Largest asset accepted, as a guard against a manifest pointing at something absurd. */
    public static final int MAX_ASSET_BYTES = 32 * 1024 * 1024;

    private static volatile boolean imageIoConfigured;

    /** What an entry is for. */
    public enum Kind {
        /** A single image. */
        SPRITE,
        /** An image cut into equally sized frames. */
        SHEET,
        /** A sound file (read by the audio layer). */
        AUDIO,
        /** A font file. */
        FONT
    }

    /**
     * One manifest entry.
     *
     * @param id the id renderers ask for
     * @param path the resource path under {@value #ASSET_ROOT}
     * @param kind what the entry is for
     * @param license the licence the file is under (recorded, never parsed)
     * @param source where the file came from (recorded, never parsed)
     * @param frameWidth frame width of a {@link Kind#SHEET}, or {@code 0}
     * @param frameHeight frame height of a {@link Kind#SHEET}, or {@code 0}
     * @param frames frame count of a {@link Kind#SHEET}, or {@code 0} for "every whole cell"
     */
    public record Entry(String id, String path, Kind kind, String license, String source,
            int frameWidth, int frameHeight, int frames) {

        /** Validates the components. */
        public Entry {
            Objects.requireNonNull(id, "id");
            Objects.requireNonNull(path, "path");
            Objects.requireNonNull(kind, "kind");
        }
    }

    private final Map<String, Entry> entries;
    private final List<String> errors = new ArrayList<>();
    private final Map<String, Optional<Sprite>> spriteCache = new LinkedHashMap<>();
    private final Map<String, Optional<SpriteSheet>> sheetCache = new LinkedHashMap<>();
    private final Map<String, Optional<byte[]>> byteCache = new LinkedHashMap<>();

    private AssetManager(Map<String, Entry> entries, List<String> parseErrors) {
        this.entries = Collections.unmodifiableMap(entries);
        this.errors.addAll(parseErrors);
    }

    /**
     * Reads {@value #MANIFEST_RESOURCE} from the classpath. A missing or malformed manifest is
     * recorded in {@link #errors()} and yields an empty registry, never an exception.
     *
     * @return the manager
     */
    public static AssetManager fromClasspath() {
        String text = readText(MANIFEST_RESOURCE);
        if (text == null) {
            List<String> errors = List.of(MANIFEST_RESOURCE + ": missing manifest");
            return new AssetManager(new LinkedHashMap<>(), errors);
        }
        return fromJson(text);
    }

    /**
     * Parses a manifest from text (tests and tools).
     *
     * @param json the manifest document
     * @return the manager
     */
    public static AssetManager fromJson(String json) {
        Map<String, Entry> entries = new LinkedHashMap<>();
        List<String> errors = new ArrayList<>();
        JsonObject root = json == null ? null : JsonCodec.parseObject(json);
        if (root == null) {
            errors.add(MANIFEST_RESOURCE + ": the manifest must be a JSON object");
            return new AssetManager(entries, errors);
        }
        JsonElement list = root.get("assets");
        if (list == null || !list.isJsonArray()) {
            errors.add(MANIFEST_RESOURCE + "#/assets: missing or not an array");
            return new AssetManager(entries, errors);
        }
        JsonArray array = list.getAsJsonArray();
        for (int i = 0; i < array.size(); i++) {
            JsonElement element = array.get(i);
            if (!element.isJsonObject()) {
                errors.add(MANIFEST_RESOURCE + "#/assets/" + i + ": entry must be an object");
                continue;
            }
            Entry entry = parseEntry(element.getAsJsonObject(), i, errors);
            if (entry == null) {
                continue;
            }
            if (entries.putIfAbsent(entry.id(), entry) != null) {
                errors.add(MANIFEST_RESOURCE + "#/assets/" + i + ": duplicate id " + entry.id());
            }
        }
        return new AssetManager(entries, errors);
    }

    /**
     * A manager with no entries at all (the state the shipped manifest produces).
     *
     * @return the manager
     */
    public static AssetManager empty() {
        return new AssetManager(new LinkedHashMap<>(), List.of());
    }

    private static Entry parseEntry(JsonObject o, int index, List<String> errors) {
        String where = MANIFEST_RESOURCE + "#/assets/" + index;
        String id = string(o, "id");
        String path = string(o, "path");
        if (id == null || id.isBlank()) {
            errors.add(where + ": missing id");
            return null;
        }
        if (path == null || path.isBlank()) {
            errors.add(where + " (" + id + "): missing path");
            return null;
        }
        String kindText = string(o, "kind");
        Kind kind;
        try {
            kind = Kind.valueOf(kindText == null ? "SPRITE"
                    : kindText.toUpperCase(Locale.ROOT).trim());
        } catch (IllegalArgumentException e) {
            errors.add(where + " (" + id + "): unknown kind " + kindText);
            return null;
        }
        return new Entry(id, normalisePath(path), kind,
                orEmpty(string(o, "license")), orEmpty(string(o, "source")),
                integer(o, "frameWidth"), integer(o, "frameHeight"), integer(o, "frames"));
    }

    /**
     * Reduces a declared path to the part below {@value #ASSET_ROOT}. Both conventions in the
     * plan are accepted: the shipped manifest documents {@code "sprites/birds/classic.png"}
     * (relative to the asset root) while §4's font entry writes
     * {@code "assets/fonts/Nunito-Regular.ttf"} (relative to the classpath root). Without this the
     * second would resolve to {@code /assets/assets/fonts/...} and never be found.
     *
     * @param path the declared path
     * @return the path relative to {@value #ASSET_ROOT}
     */
    private static String normalisePath(String path) {
        String out = path.startsWith("/") ? path.substring(1) : path;
        return out.startsWith("assets/") ? out.substring("assets/".length()) : out;
    }

    private static String orEmpty(String value) {
        return value == null ? "" : value;
    }

    private static String string(JsonObject o, String key) {
        JsonElement value = o.get(key);
        return value != null && value.isJsonPrimitive() && value.getAsJsonPrimitive().isString()
                ? value.getAsString() : null;
    }

    private static int integer(JsonObject o, String key) {
        JsonElement value = o.get(key);
        if (value == null || !value.isJsonPrimitive() || !value.getAsJsonPrimitive().isNumber()) {
            return 0;
        }
        try {
            return value.getAsInt();
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    /**
     * The declared entries by id, in manifest order.
     *
     * @return an unmodifiable view
     */
    public Map<String, Entry> entries() {
        return entries;
    }

    /**
     * Everything that went wrong while parsing the manifest or loading an asset.
     *
     * @return an unmodifiable snapshot, empty when nothing failed
     */
    public List<String> errors() {
        return List.copyOf(errors);
    }

    /**
     * Whether an id is declared (it may still fail to load).
     *
     * @param id the id
     * @return {@code true} when the manifest lists it
     */
    public boolean has(String id) {
        return entries.containsKey(id);
    }

    /**
     * Loads an image asset, or answers empty so the caller draws procedural art.
     *
     * @param id the manifest id
     * @return the sprite, or empty when the id is not declared or could not be read
     */
    public Optional<Sprite> sprite(String id) {
        if (id == null) {
            return Optional.empty();
        }
        Optional<Sprite> cached = spriteCache.get(id);
        if (cached != null) {
            return cached;
        }
        Optional<Sprite> loaded = loadSprite(id);
        spriteCache.put(id, loaded);
        return loaded;
    }

    /**
     * Loads a sheet asset and cuts it into frames, or answers empty.
     *
     * @param id the manifest id (its {@code kind} must be {@link Kind#SHEET})
     * @return the sheet, or empty when the id is not declared or could not be read
     */
    public Optional<SpriteSheet> sheet(String id) {
        if (id == null) {
            return Optional.empty();
        }
        Optional<SpriteSheet> cached = sheetCache.get(id);
        if (cached != null) {
            return cached;
        }
        Optional<SpriteSheet> loaded = loadSheet(id);
        sheetCache.put(id, loaded);
        return loaded;
    }

    /**
     * Reads a non-image asset (audio, font) as bytes; the audio and font layers decode it
     * themselves.
     *
     * @param id the manifest id
     * @return the bytes, or empty when the id is not declared or could not be read
     */
    public Optional<byte[]> bytes(String id) {
        if (id == null) {
            return Optional.empty();
        }
        Optional<byte[]> cached = byteCache.get(id);
        if (cached != null) {
            return cached;
        }
        Optional<byte[]> loaded = loadBytes(id);
        byteCache.put(id, loaded);
        return loaded;
    }

    /** Drops every cached image so a later call reloads from the classpath. */
    public void clearCache() {
        spriteCache.clear();
        sheetCache.clear();
        byteCache.clear();
    }

    private Optional<Sprite> loadSprite(String id) {
        Entry entry = entries.get(id);
        if (entry == null) {
            return Optional.empty();
        }
        if (entry.kind() != Kind.SPRITE && entry.kind() != Kind.SHEET) {
            errors.add(entry.path() + " (" + id + "): kind " + entry.kind() + " is not an image");
            return Optional.empty();
        }
        BufferedImage image = readImage(entry, id);
        return image == null ? Optional.empty() : Optional.of(new Sprite(id, compatible(image)));
    }

    private Optional<SpriteSheet> loadSheet(String id) {
        Entry entry = entries.get(id);
        if (entry == null) {
            return Optional.empty();
        }
        Optional<Sprite> sprite = sprite(id);
        if (sprite.isEmpty()) {
            return Optional.empty();
        }
        int fw = entry.frameWidth() > 0 ? entry.frameWidth() : sprite.get().width();
        int fh = entry.frameHeight() > 0 ? entry.frameHeight() : sprite.get().height();
        return Optional.of(new SpriteSheet(sprite.get(), fw, fh, entry.frames()));
    }

    private Optional<byte[]> loadBytes(String id) {
        Entry entry = entries.get(id);
        if (entry == null) {
            return Optional.empty();
        }
        byte[] data = readBytes(ASSET_ROOT + entry.path());
        if (data == null) {
            errors.add(entry.path() + " (" + id + "): missing resource");
            return Optional.empty();
        }
        return Optional.of(data);
    }

    private BufferedImage readImage(Entry entry, String id) {
        configureImageIo();
        try (InputStream in = AssetManager.class.getResourceAsStream(ASSET_ROOT + entry.path())) {
            if (in == null) {
                errors.add(entry.path() + " (" + id + "): missing resource");
                return null;
            }
            BufferedImage image = ImageIO.read(in);
            if (image == null) {
                errors.add(entry.path() + " (" + id + "): no decoder for this file");
            }
            return image;
        } catch (IOException | RuntimeException e) {
            errors.add(entry.path() + " (" + id + "): " + e);
            return null;
        }
    }

    /**
     * Copies an image into the format the screen uses, so blits do not convert per frame. With
     * no display (headless tests, {@code --headless-run}) the decoded image is kept as it is.
     *
     * @param source the decoded image
     * @return a compatible copy, or {@code source}
     */
    private static BufferedImage compatible(BufferedImage source) {
        try {
            if (GraphicsEnvironment.isHeadless()) {
                return source;
            }
            GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment()
                    .getDefaultScreenDevice().getDefaultConfiguration();
            if (gc == null) {
                return source;
            }
            BufferedImage copy = gc.createCompatibleImage(source.getWidth(), source.getHeight(),
                    Transparency.TRANSLUCENT);
            java.awt.Graphics2D g = copy.createGraphics();
            try {
                g.drawImage(source, 0, 0, null);
            } finally {
                g.dispose();
            }
            return copy;
        } catch (AWTError | RuntimeException e) {
            return source;
        }
    }

    private static synchronized void configureImageIo() {
        if (!imageIoConfigured) {
            ImageIO.setUseCache(false);
            imageIoConfigured = true;
        }
    }

    private static String readText(String resource) {
        byte[] data = readBytes(resource);
        return data == null ? null : new String(data, StandardCharsets.UTF_8);
    }

    private static byte[] readBytes(String resource) {
        try (InputStream in = AssetManager.class.getResourceAsStream(resource)) {
            if (in == null) {
                return null;
            }
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[8192];
            int read;
            int total = 0;
            while ((read = in.read(buffer)) >= 0) {
                total += read;
                if (total > MAX_ASSET_BYTES) {
                    return null;
                }
                out.write(buffer, 0, read);
            }
            return out.toByteArray();
        } catch (IOException e) {
            return null;
        }
    }

    @Override
    public String toString() {
        return "AssetManager[entries=" + entries.size() + " errors=" + errors.size() + "]";
    }
}
